// <auto-generated />
using System;
using GambianMuslimCommunity.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GambianMuslimCommunity.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250913212416_AddMembersTable")]
    partial class AddMembersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GambianMuslimCommunity.Models.AdminActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ActivityDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("AdminUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Entity")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId");

                    b.ToTable("AdminActivityLogs");
                });

            modelBuilder.Entity("GambianMuslimCommunity.Models.AdminSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminUserId")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("LastActivity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("LoginDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId");

                    b.ToTable("AdminSessions");
                });

            modelBuilder.Entity("GambianMuslimCommunity.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfilePicture")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Admin");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AdminUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 8, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Email = "admin@gambianmuslimcommunity.org",
                            FullName = "System Administrator",
                            IsActive = true,
                            PasswordHash = "$2a$11$N.Kt4q5BKkYLGgpF.jKMu.J0WpFbOJGnvf9..jvVt8OAVS5PCIK3y",
                            Role = "SuperAdmin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 8, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Email = "ab.diaby@gmail.com",
                            FullName = "Abou Diaby",
                            IsActive = true,
                            PasswordHash = "$2a$11$BTi6nbWb.ghlB/7/m1vK0e8F29NoZesgDleVVVbU9L0feRaU6vn/S",
                            Role = "SuperAdmin",
                            Username = "aboudiaby"
                        });
                });

            modelBuilder.Entity("GambianMuslimCommunity.Models.CommunityEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("CommunityEvents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Join us for a community iftar during Ramadan",
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            EventDate = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            EventType = "Religious",
                            Location = "Community Center",
                            StartTime = new TimeSpan(0, 18, 0, 0, 0),
                            Title = "Community Iftar"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Learn about Islamic history and jurisprudence",
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            EventDate = new DateTime(2025, 10, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            EventType = "Educational",
                            Location = "Main Hall",
                            StartTime = new TimeSpan(0, 14, 0, 0, 0),
                            Title = "Islamic Studies Workshop"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Islamic education and activities for young Muslims",
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            EventDate = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            EventType = "Youth",
                            Location = "Youth Center",
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "Youth Program"
                        });
                });

            modelBuilder.Entity("GambianMuslimCommunity.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReadBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ReadDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("GambianMuslimCommunity.Models.ContributionTracker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AverageContribution")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ContributionCount")
                        .HasColumnType("int");

                    b.Property<string>("ContributionNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContributorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FirstContributionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActiveContributor")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastContributionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PreferredPaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalContributions")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ContributionTrackers");
                });

            modelBuilder.Entity("GambianMuslimCommunity.Models.MasjidDonation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DonationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("DonorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("bit");

                    b.Property<int>("MasjidProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PayPalPayerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PayPalPaymentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("MasjidProjectId");

                    b.ToTable("MasjidDonations");
                });

            modelBuilder.Entity("GambianMuslimCommunity.Models.MasjidProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("CurrentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("TargetCompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Updates")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("MasjidProjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 8, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            CurrentAmount = 125000m,
                            Description = "Alhamdulillah, by the grace of Allah (SWT), we are embarking on building a new masjid to serve our growing Gambian Muslim community in Minnesota. This masjid will provide a dedicated space for our five daily prayers, Jummah prayers, Islamic education, and community gatherings. The new facility will include a main prayer hall, separate women's prayer area, classrooms for Islamic studies, community kitchen, and parking facilities.",
                            ImageUrl = "/images/masjid-project.jpg",
                            IsActive = true,
                            IsFeatured = true,
                            Location = "Minneapolis, MN - 15 minutes from current location",
                            StartDate = new DateTime(2025, 8, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            Status = "Fundraising",
                            TargetAmount = 500000m,
                            TargetCompletionDate = new DateTime(2026, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "New Masjid Building Project",
                            Updates = "Alhamdulillah! We have secured the land and received initial construction permits. Phase 1 fundraising is 25% complete. May Allah (SWT) bless all our donors and supporters."
                        });
                });

            modelBuilder.Entity("GambianMuslimCommunity.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ApprovedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EmergencyContactName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmergencyContactPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EmergencyContactRelationship")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MembershipStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("English");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("ReceiveEmailNotifications")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("ReceiveSmsNotifications")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("RegistrationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Members");
                });

            modelBuilder.Entity("GambianMuslimCommunity.Models.MemberActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ActivityDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("AdminUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Entity")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId");

                    b.HasIndex("MemberId");

                    b.ToTable("MemberActivityLogs");
                });

            modelBuilder.Entity("GambianMuslimCommunity.Models.MembershipSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("ModifiedById")
                        .HasColumnType("int");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("SettingKey")
                        .IsUnique();

                    b.ToTable("MembershipSettings");
                });

            modelBuilder.Entity("GambianMuslimCommunity.Models.PrayerTimeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("PrayerTimes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Minneapolis, MN",
                            Date = new DateTime(2025, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            Name = "Fajr",
                            Time = new TimeSpan(0, 5, 45, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            City = "Minneapolis, MN",
                            Date = new DateTime(2025, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            Name = "Dhuhr",
                            Time = new TimeSpan(0, 12, 15, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            City = "Minneapolis, MN",
                            Date = new DateTime(2025, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            Name = "Asr",
                            Time = new TimeSpan(0, 14, 30, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            City = "Minneapolis, MN",
                            Date = new DateTime(2025, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            Name = "Maghrib",
                            Time = new TimeSpan(0, 16, 45, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            City = "Minneapolis, MN",
                            Date = new DateTime(2025, 9, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            Name = "Isha",
                            Time = new TimeSpan(0, 18, 15, 0, 0)
                        });
                });

            modelBuilder.Entity("GambianMuslimCommunity.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("IconClass")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Daily congregational prayers, Jummah prayers, and special occasion prayers including Eid celebrations.",
                            IconClass = "fas fa-pray",
                            IsActive = true,
                            Title = "Prayer Services"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Quran classes for children and adults, Islamic studies, Arabic language instruction, and religious guidance.",
                            IconClass = "fas fa-book-quran",
                            IsActive = true,
                            Title = "Islamic Education"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Counseling services, family support, assistance for new immigrants, and community welfare programs.",
                            IconClass = "fas fa-heart",
                            IsActive = true,
                            Title = "Community Support"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Gambian cultural celebrations, Islamic holidays, community gatherings, and interfaith dialogue events.",
                            IconClass = "fas fa-calendar-alt",
                            IsActive = true,
                            Title = "Cultural Events"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Islamic marriage ceremonies, family counseling, youth programs, and life event celebrations.",
                            IconClass = "fas fa-ring",
                            IsActive = true,
                            Title = "Marriage & Family"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Zakat collection and distribution, charitable giving coordination, and community assistance programs.",
                            IconClass = "fas fa-donate",
                            IsActive = true,
                            Title = "Zakat & Charity"
                        });
                });

            modelBuilder.Entity("GambianMuslimCommunity.Models.SiteSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("General");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("SettingKey", "Category")
                        .IsUnique();

                    b.ToTable("SiteSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "General",
                            Description = "The name of the website",
                            IsActive = true,
                            LastModified = new DateTime(2025, 9, 13, 16, 24, 15, 858, DateTimeKind.Local).AddTicks(4947),
                            ModifiedBy = "",
                            SettingKey = "SiteName",
                            SettingValue = "Gambian Muslim Community in Minnesota"
                        },
                        new
                        {
                            Id = 2,
                            Category = "General",
                            Description = "Brief description of the website",
                            IsActive = true,
                            LastModified = new DateTime(2025, 9, 13, 16, 24, 15, 858, DateTimeKind.Local).AddTicks(4951),
                            ModifiedBy = "",
                            SettingKey = "SiteDescription",
                            SettingValue = "Serving the Gambian Muslim community in Minnesota with Islamic services, education, and support"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Contact",
                            Description = "Primary contact email address",
                            IsActive = true,
                            LastModified = new DateTime(2025, 9, 13, 16, 24, 15, 858, DateTimeKind.Local).AddTicks(4953),
                            ModifiedBy = "",
                            SettingKey = "ContactEmail",
                            SettingValue = "info@gambianmuslimcommunity.org"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Contact",
                            Description = "Primary contact phone number",
                            IsActive = true,
                            LastModified = new DateTime(2025, 9, 13, 16, 24, 15, 858, DateTimeKind.Local).AddTicks(4955),
                            ModifiedBy = "",
                            SettingKey = "ContactPhone",
                            SettingValue = "(612) 555-0123"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Contact",
                            Description = "Physical address",
                            IsActive = true,
                            LastModified = new DateTime(2025, 9, 13, 16, 24, 15, 858, DateTimeKind.Local).AddTicks(4957),
                            ModifiedBy = "",
                            SettingKey = "Address",
                            SettingValue = "123 Main Street"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Contact",
                            Description = "City",
                            IsActive = true,
                            LastModified = new DateTime(2025, 9, 13, 16, 24, 15, 858, DateTimeKind.Local).AddTicks(4959),
                            ModifiedBy = "",
                            SettingKey = "City",
                            SettingValue = "Minneapolis"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Contact",
                            Description = "State",
                            IsActive = true,
                            LastModified = new DateTime(2025, 9, 13, 16, 24, 15, 858, DateTimeKind.Local).AddTicks(4961),
                            ModifiedBy = "",
                            SettingKey = "State",
                            SettingValue = "MN"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Contact",
                            Description = "ZIP code",
                            IsActive = true,
                            LastModified = new DateTime(2025, 9, 13, 16, 24, 15, 858, DateTimeKind.Local).AddTicks(4963),
                            ModifiedBy = "",
                            SettingKey = "ZipCode",
                            SettingValue = "55401"
                        },
                        new
                        {
                            Id = 9,
                            Category = "General",
                            Description = "Name of the community imam",
                            IsActive = true,
                            LastModified = new DateTime(2025, 9, 13, 16, 24, 15, 858, DateTimeKind.Local).AddTicks(4964),
                            ModifiedBy = "",
                            SettingKey = "ImamName",
                            SettingValue = "Imam Abdullah Jallow"
                        },
                        new
                        {
                            Id = 20,
                            Category = "General",
                            Description = "Imam's welcome message to the community",
                            IsActive = true,
                            LastModified = new DateTime(2025, 9, 13, 16, 24, 15, 858, DateTimeKind.Local).AddTicks(4966),
                            ModifiedBy = "",
                            SettingKey = "ImamWelcomeMessage",
                            SettingValue = "Assalamu Alaikum wa Rahmatullahi wa Barakatuh, dear brothers and sisters. Welcome to our vibrant Gambian Muslim Community in Minnesota. May Allah (SWT) bless you and your families as we come together to worship, learn, and support one another in faith. Our community is a place where Islamic values flourish, cultural heritage is preserved, and bonds of brotherhood and sisterhood grow stronger each day."
                        },
                        new
                        {
                            Id = 21,
                            Category = "General",
                            Description = "URL for the Imam's photo",
                            IsActive = true,
                            LastModified = new DateTime(2025, 9, 13, 16, 24, 15, 858, DateTimeKind.Local).AddTicks(4968),
                            ModifiedBy = "",
                            SettingKey = "ImamImageUrl",
                            SettingValue = "/images/imam-placeholder.jpg"
                        },
                        new
                        {
                            Id = 22,
                            Category = "General",
                            Description = "Imam's title or position",
                            IsActive = true,
                            LastModified = new DateTime(2025, 9, 13, 16, 24, 15, 858, DateTimeKind.Local).AddTicks(4970),
                            ModifiedBy = "",
                            SettingKey = "ImamTitle",
                            SettingValue = "Community Imam & Spiritual Leader"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Social",
                            Description = "Facebook page URL",
                            IsActive = true,
                            LastModified = new DateTime(2025, 9, 13, 16, 24, 15, 858, DateTimeKind.Local).AddTicks(4972),
                            ModifiedBy = "",
                            SettingKey = "FacebookUrl",
                            SettingValue = "https://facebook.com/gambianmuslimcommunity"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Social",
                            Description = "Instagram page URL",
                            IsActive = true,
                            LastModified = new DateTime(2025, 9, 13, 16, 24, 15, 858, DateTimeKind.Local).AddTicks(4973),
                            ModifiedBy = "",
                            SettingKey = "InstagramUrl",
                            SettingValue = "https://instagram.com/gambianmuslimmn"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Social",
                            Description = "WhatsApp contact number",
                            IsActive = true,
                            LastModified = new DateTime(2025, 9, 13, 16, 24, 15, 858, DateTimeKind.Local).AddTicks(4975),
                            ModifiedBy = "",
                            SettingKey = "WhatsAppNumber",
                            SettingValue = "+16125550123"
                        },
                        new
                        {
                            Id = 13,
                            Category = "General",
                            Description = "Website logo URL",
                            IsActive = true,
                            LastModified = new DateTime(2025, 9, 13, 16, 24, 15, 858, DateTimeKind.Local).AddTicks(4977),
                            ModifiedBy = "",
                            SettingKey = "LogoUrl",
                            SettingValue = "/images/logo.png"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Email",
                            Description = "SMTP server for sending emails",
                            IsActive = true,
                            LastModified = new DateTime(2025, 9, 13, 16, 24, 15, 858, DateTimeKind.Local).AddTicks(4979),
                            ModifiedBy = "",
                            SettingKey = "SmtpServer",
                            SettingValue = "smtp.gmail.com"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Email",
                            Description = "SMTP server port",
                            IsActive = true,
                            LastModified = new DateTime(2025, 9, 13, 16, 24, 15, 858, DateTimeKind.Local).AddTicks(4981),
                            ModifiedBy = "",
                            SettingKey = "SmtpPort",
                            SettingValue = "587"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Email",
                            Description = "From email address for system emails",
                            IsActive = true,
                            LastModified = new DateTime(2025, 9, 13, 16, 24, 15, 858, DateTimeKind.Local).AddTicks(4983),
                            ModifiedBy = "",
                            SettingKey = "FromEmail",
                            SettingValue = "noreply@gambianmuslimcommunity.org"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Email",
                            Description = "From name for system emails",
                            IsActive = true,
                            LastModified = new DateTime(2025, 9, 13, 16, 24, 15, 858, DateTimeKind.Local).AddTicks(4984),
                            ModifiedBy = "",
                            SettingKey = "FromName",
                            SettingValue = "Gambian Muslim Community"
                        });
                });

            modelBuilder.Entity("GambianMuslimCommunity.Models.AdminActivityLog", b =>
                {
                    b.HasOne("GambianMuslimCommunity.Models.AdminUser", "AdminUser")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("GambianMuslimCommunity.Models.AdminSession", b =>
                {
                    b.HasOne("GambianMuslimCommunity.Models.AdminUser", "AdminUser")
                        .WithMany("Sessions")
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("GambianMuslimCommunity.Models.MasjidDonation", b =>
                {
                    b.HasOne("GambianMuslimCommunity.Models.MasjidProject", "MasjidProject")
                        .WithMany()
                        .HasForeignKey("MasjidProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasjidProject");
                });

            modelBuilder.Entity("GambianMuslimCommunity.Models.Member", b =>
                {
                    b.HasOne("GambianMuslimCommunity.Models.AdminUser", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApprovedBy");
                });

            modelBuilder.Entity("GambianMuslimCommunity.Models.MemberActivityLog", b =>
                {
                    b.HasOne("GambianMuslimCommunity.Models.AdminUser", "AdminUser")
                        .WithMany()
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GambianMuslimCommunity.Models.Member", "Member")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminUser");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("GambianMuslimCommunity.Models.MembershipSettings", b =>
                {
                    b.HasOne("GambianMuslimCommunity.Models.AdminUser", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("GambianMuslimCommunity.Models.AdminUser", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("GambianMuslimCommunity.Models.Member", b =>
                {
                    b.Navigation("ActivityLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
