// <auto-generated />
using System;
using GambianMuslimCommunity.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GambianMuslimCommunity.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250818132409_AddPayPalFieldsToMasjidDonation")]
    partial class AddPayPalFieldsToMasjidDonation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GambianMuslimCommunity.Models.CommunityEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("CommunityEvents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Join us for a community iftar during Ramadan",
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            EventDate = new DateTime(2025, 8, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            EventType = "Religious",
                            Location = "Community Center",
                            StartTime = new TimeSpan(0, 18, 0, 0, 0),
                            Title = "Community Iftar"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Learn about Islamic history and jurisprudence",
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            EventDate = new DateTime(2025, 9, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            EventType = "Educational",
                            Location = "Main Hall",
                            StartTime = new TimeSpan(0, 14, 0, 0, 0),
                            Title = "Islamic Studies Workshop"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Islamic education and activities for young Muslims",
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            EventDate = new DateTime(2025, 9, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            EventType = "Youth",
                            Location = "Youth Center",
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "Youth Program"
                        });
                });

            modelBuilder.Entity("GambianMuslimCommunity.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("GambianMuslimCommunity.Models.MasjidDonation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DonationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("DonorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("bit");

                    b.Property<int>("MasjidProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PayPalPayerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PayPalPaymentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("MasjidProjectId");

                    b.ToTable("MasjidDonations");
                });

            modelBuilder.Entity("GambianMuslimCommunity.Models.MasjidProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("CurrentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("TargetCompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Updates")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("MasjidProjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 7, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            CurrentAmount = 125000m,
                            Description = "Alhamdulillah, by the grace of Allah (SWT), we are embarking on building a new masjid to serve our growing Gambian Muslim community in Minnesota. This masjid will provide a dedicated space for our five daily prayers, Jummah prayers, Islamic education, and community gatherings. The new facility will include a main prayer hall, separate women's prayer area, classrooms for Islamic studies, community kitchen, and parking facilities.",
                            ImageUrl = "/images/masjid-project.jpg",
                            IsActive = true,
                            IsFeatured = true,
                            Location = "Minneapolis, MN - 15 minutes from current location",
                            StartDate = new DateTime(2025, 7, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Status = "Fundraising",
                            TargetAmount = 500000m,
                            TargetCompletionDate = new DateTime(2026, 8, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "New Masjid Building Project",
                            Updates = "Alhamdulillah! We have secured the land and received initial construction permits. Phase 1 fundraising is 25% complete. May Allah (SWT) bless all our donors and supporters."
                        });
                });

            modelBuilder.Entity("GambianMuslimCommunity.Models.PrayerTimeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("PrayerTimes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Minneapolis, MN",
                            Date = new DateTime(2025, 8, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            Name = "Fajr",
                            Time = new TimeSpan(0, 5, 45, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            City = "Minneapolis, MN",
                            Date = new DateTime(2025, 8, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            Name = "Dhuhr",
                            Time = new TimeSpan(0, 12, 15, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            City = "Minneapolis, MN",
                            Date = new DateTime(2025, 8, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            Name = "Asr",
                            Time = new TimeSpan(0, 14, 30, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            City = "Minneapolis, MN",
                            Date = new DateTime(2025, 8, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            Name = "Maghrib",
                            Time = new TimeSpan(0, 16, 45, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            City = "Minneapolis, MN",
                            Date = new DateTime(2025, 8, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            Name = "Isha",
                            Time = new TimeSpan(0, 18, 15, 0, 0)
                        });
                });

            modelBuilder.Entity("GambianMuslimCommunity.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("IconClass")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Daily congregational prayers, Jummah prayers, and special occasion prayers including Eid celebrations.",
                            IconClass = "fas fa-pray",
                            IsActive = true,
                            Title = "Prayer Services"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Quran classes for children and adults, Islamic studies, Arabic language instruction, and religious guidance.",
                            IconClass = "fas fa-book-quran",
                            IsActive = true,
                            Title = "Islamic Education"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Counseling services, family support, assistance for new immigrants, and community welfare programs.",
                            IconClass = "fas fa-heart",
                            IsActive = true,
                            Title = "Community Support"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Gambian cultural celebrations, Islamic holidays, community gatherings, and interfaith dialogue events.",
                            IconClass = "fas fa-calendar-alt",
                            IsActive = true,
                            Title = "Cultural Events"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Islamic marriage ceremonies, family counseling, youth programs, and life event celebrations.",
                            IconClass = "fas fa-ring",
                            IsActive = true,
                            Title = "Marriage & Family"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Zakat collection and distribution, charitable giving coordination, and community assistance programs.",
                            IconClass = "fas fa-donate",
                            IsActive = true,
                            Title = "Zakat & Charity"
                        });
                });

            modelBuilder.Entity("GambianMuslimCommunity.Models.MasjidDonation", b =>
                {
                    b.HasOne("GambianMuslimCommunity.Models.MasjidProject", "MasjidProject")
                        .WithMany()
                        .HasForeignKey("MasjidProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasjidProject");
                });
#pragma warning restore 612, 618
        }
    }
}
